[package]
name = "cybermen"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.1"
tokio = { version = "1.35.1", features = ["full"] }
tokio-core = { version = "0.1.18" }
tuntap = { path = "src/modules/tuntap" }
